// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using STEMwise.Infrastructure.Data;

#nullable disable

namespace STEMwise.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260412055540_InitialAzureSql")]
    partial class InitialAzureSql
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("STEMwise.Domain.Entities.ApiCache", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ApiSource")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CacheKey")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FetchedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ResponseData")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TtlHours")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("ApiCaches");
                });

            modelBuilder.Entity("STEMwise.Domain.Entities.Country", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CurrencyCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FlagEmoji")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("IntlEmploymentRate")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("LanguageBarrier")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("PostStudyVisaMonths")
                        .HasColumnType("int");

                    b.Property<string>("PostStudyVisaName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PrDifficulty")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PrPathway")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("WorkVisaRisk")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("Countries");

                    b.HasData(
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111111"),
                            Code = "US",
                            CreatedAt = new DateTime(2026, 4, 12, 5, 55, 38, 722, DateTimeKind.Utc).AddTicks(7843),
                            CurrencyCode = "USD",
                            FlagEmoji = "🇺🇸",
                            IntlEmploymentRate = 85.5m,
                            LanguageBarrier = "None",
                            Name = "United States",
                            PostStudyVisaMonths = 36,
                            PostStudyVisaName = "STEM OPT",
                            PrDifficulty = "High",
                            PrPathway = "H-1B → EB-2/3",
                            WorkVisaRisk = "High"
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222222"),
                            Code = "GB",
                            CreatedAt = new DateTime(2026, 4, 12, 5, 55, 38, 723, DateTimeKind.Utc).AddTicks(7244),
                            CurrencyCode = "GBP",
                            FlagEmoji = "🇬🇧",
                            IntlEmploymentRate = 78.2m,
                            LanguageBarrier = "None",
                            Name = "United Kingdom",
                            PostStudyVisaMonths = 24,
                            PostStudyVisaName = "Graduate Route",
                            PrDifficulty = "Medium",
                            PrPathway = "Skilled Worker → ILR",
                            WorkVisaRisk = "Medium"
                        });
                });

            modelBuilder.Entity("STEMwise.Domain.Entities.Employer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("AvgSponsoredSalary")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("H1BFilingsTotal")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.PrimitiveCollection<string>("PrimaryStemFields")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("SponsorScore")
                        .HasColumnType("int");

                    b.PrimitiveCollection<string>("TopCities")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Employers");

                    b.HasData(
                        new
                        {
                            Id = new Guid("5af3f54b-832b-47b2-b2ab-a35814f69c99"),
                            AvgSponsoredSalary = 165000,
                            CreatedAt = new DateTime(2026, 4, 12, 5, 55, 38, 726, DateTimeKind.Utc).AddTicks(6175),
                            H1BFilingsTotal = 12500,
                            Name = "Google",
                            PrimaryStemFields = "[\"Software Engineering\",\"Data Science\",\"AI\"]",
                            SponsorScore = 98,
                            TopCities = "[\"Mountain View\",\"San Francisco\",\"Austin\",\"New York\"]"
                        },
                        new
                        {
                            Id = new Guid("426887e3-d5c5-40ff-8f56-336fb3f1a1bc"),
                            AvgSponsoredSalary = 155000,
                            CreatedAt = new DateTime(2026, 4, 12, 5, 55, 38, 726, DateTimeKind.Utc).AddTicks(6969),
                            H1BFilingsTotal = 35000,
                            Name = "Amazon",
                            PrimaryStemFields = "[\"Cloud Computing\",\"Software Engineering\",\"Product Management\"]",
                            SponsorScore = 95,
                            TopCities = "[\"Seattle\",\"Austin\",\"Arlington\",\"San Francisco\"]"
                        },
                        new
                        {
                            Id = new Guid("d187a922-f9c8-4b31-aaee-dc81be7d276c"),
                            AvgSponsoredSalary = 175000,
                            CreatedAt = new DateTime(2026, 4, 12, 5, 55, 38, 726, DateTimeKind.Utc).AddTicks(6993),
                            H1BFilingsTotal = 8500,
                            Name = "Meta",
                            PrimaryStemFields = "[\"Product Engineering\",\"Data Engineering\"]",
                            SponsorScore = 92,
                            TopCities = "[\"Menlo Park\",\"San Francisco\",\"Seattle\",\"Austin\"]"
                        },
                        new
                        {
                            Id = new Guid("42f0c79c-37ed-4260-bff6-9686c4d34665"),
                            AvgSponsoredSalary = 145000,
                            CreatedAt = new DateTime(2026, 4, 12, 5, 55, 38, 726, DateTimeKind.Utc).AddTicks(7004),
                            H1BFilingsTotal = 2100,
                            Name = "Tesla",
                            PrimaryStemFields = "[\"Mechanical Engineering\",\"Software Engineering\",\"AI\"]",
                            SponsorScore = 88,
                            TopCities = "[\"Austin\",\"Fremont\",\"Palo Alto\"]"
                        });
                });

            modelBuilder.Entity("STEMwise.Domain.Entities.FxRateCache", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("BaseCurrency")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FetchedAt")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("Rate")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("TargetCurrency")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("BaseCurrency", "TargetCurrency")
                        .IsUnique();

                    b.ToTable("FxRateCaches");
                });

            modelBuilder.Entity("STEMwise.Domain.Entities.H1BStatistic", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("FiscalYear")
                        .HasColumnType("int");

                    b.Property<int?>("SalaryCeiling")
                        .HasColumnType("int");

                    b.Property<int?>("SalaryFloor")
                        .HasColumnType("int");

                    b.Property<decimal>("SelectionRate")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("TotalRegistrations")
                        .HasColumnType("int");

                    b.Property<int?>("TotalSelected")
                        .HasColumnType("int");

                    b.Property<int>("WageLevel")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("H1BStatistics");
                });

            modelBuilder.Entity("STEMwise.Domain.Entities.LCADisclosure", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CaseStatus")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DecisionDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("EmployerName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("JobTitle")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SocCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("WageLevel")
                        .HasColumnType("int");

                    b.Property<int>("WageOffered")
                        .HasColumnType("int");

                    b.Property<string>("WorksiteCity")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("WorksiteState")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("LCADisclosures");
                });

            modelBuilder.Entity("STEMwise.Domain.Entities.LoanConfig", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Amount")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("InterestRate")
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("LoanName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("LoanType")
                        .HasColumnType("int");

                    b.Property<Guid>("ProfileId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("RepaymentTermYears")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProfileId");

                    b.ToTable("LoanConfigs");
                });

            modelBuilder.Entity("STEMwise.Domain.Entities.Profile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("AnnualLivingCost")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("AnnualTuition")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("DegreeLevel")
                        .HasColumnType("int");

                    b.Property<string>("DegreeName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HomeCurrency")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IntakeTerm")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("LoanAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("LoanInterestRate")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Nationality")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ProgramDurationYears")
                        .HasColumnType("int");

                    b.Property<string>("Specialization")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StemField")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TargetCity")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("TargetSalary")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("TargetUniversity")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.ToTable("Profiles");
                });

            modelBuilder.Entity("STEMwise.Domain.Entities.Program", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("AvgStartingSalary")
                        .HasColumnType("int");

                    b.Property<string>("CipCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("DegreeLevel")
                        .HasColumnType("int");

                    b.Property<decimal>("DurationYears")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("EmploymentRate1Yr")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StemField")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("StemOptEligible")
                        .HasColumnType("bit");

                    b.Property<Guid>("UniversityId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UniversityId");

                    b.ToTable("Programs");
                });

            modelBuilder.Entity("STEMwise.Domain.Entities.ROIReport", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("BreakevenSalary")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("DebtToIncomeRatio")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("EarningsPremiumPct")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("H1BProbability")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("H1BWageLevel")
                        .HasColumnType("int");

                    b.Property<string>("InputSnapshot")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("OptAnnualSalary")
                        .HasColumnType("int");

                    b.PrimitiveCollection<string>("OptimizationTips")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("PaybackPeriodYears")
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid>("ProfileId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("RoiLabel")
                        .HasColumnType("int");

                    b.Property<int>("RoiScore")
                        .HasColumnType("int");

                    b.Property<decimal>("TotalCostHome")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("TotalCostUsd")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProfileId");

                    b.ToTable("ROIReports");
                });

            modelBuilder.Entity("STEMwise.Domain.Entities.SalaryBenchmark", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("AnnualSalary")
                        .HasColumnType("int");

                    b.Property<Guid>("CountryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("MetroArea")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Percentile25")
                        .HasColumnType("int");

                    b.Property<int?>("Percentile50")
                        .HasColumnType("int");

                    b.Property<int?>("Percentile75")
                        .HasColumnType("int");

                    b.Property<string>("SocCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Source")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StemField")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("WageLevel")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CountryId");

                    b.ToTable("SalaryBenchmarks");
                });

            modelBuilder.Entity("STEMwise.Domain.Entities.SavedScenario", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("AdjustedRoi")
                        .HasColumnType("int");

                    b.Property<string>("AlternativePaths")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("BaseRoi")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("ImpactDelta")
                        .HasColumnType("int");

                    b.Property<Guid>("ProfileId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ScenarioParams")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ScenarioType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ProfileId");

                    b.ToTable("SavedScenarios");
                });

            modelBuilder.Entity("STEMwise.Domain.Entities.University", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("AnnualLivingCost")
                        .HasColumnType("int");

                    b.Property<int>("AnnualTuitionIntl")
                        .HasColumnType("int");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("CountryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RankingTier")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ScorecardId")
                        .HasColumnType("int");

                    b.Property<string>("StateProvince")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CountryId");

                    b.ToTable("Universities");
                });

            modelBuilder.Entity("STEMwise.Domain.Entities.UserUniversity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("CustomLivingCost")
                        .HasColumnType("int");

                    b.Property<int?>("CustomTuition")
                        .HasColumnType("int");

                    b.Property<bool>("IsPrimary")
                        .HasColumnType("bit");

                    b.Property<Guid>("ProfileId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("ProgramId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<Guid>("UniversityId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ProfileId");

                    b.HasIndex("ProgramId");

                    b.HasIndex("UniversityId");

                    b.ToTable("UserUniversities");
                });

            modelBuilder.Entity("STEMwise.Domain.Entities.VisaConfig", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("ExpectedSalary")
                        .HasColumnType("int");

                    b.Property<Guid>("ProfileId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("TargetCity")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TargetEmployerTier")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TargetRole")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("VisaPath")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProfileId");

                    b.ToTable("VisaConfigs");
                });

            modelBuilder.Entity("STEMwise.Domain.Entities.LoanConfig", b =>
                {
                    b.HasOne("STEMwise.Domain.Entities.Profile", "Profile")
                        .WithMany("LoanConfigs")
                        .HasForeignKey("ProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Profile");
                });

            modelBuilder.Entity("STEMwise.Domain.Entities.Program", b =>
                {
                    b.HasOne("STEMwise.Domain.Entities.University", "University")
                        .WithMany("Programs")
                        .HasForeignKey("UniversityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("University");
                });

            modelBuilder.Entity("STEMwise.Domain.Entities.ROIReport", b =>
                {
                    b.HasOne("STEMwise.Domain.Entities.Profile", "Profile")
                        .WithMany()
                        .HasForeignKey("ProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Profile");
                });

            modelBuilder.Entity("STEMwise.Domain.Entities.SalaryBenchmark", b =>
                {
                    b.HasOne("STEMwise.Domain.Entities.Country", "Country")
                        .WithMany()
                        .HasForeignKey("CountryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Country");
                });

            modelBuilder.Entity("STEMwise.Domain.Entities.SavedScenario", b =>
                {
                    b.HasOne("STEMwise.Domain.Entities.Profile", "Profile")
                        .WithMany()
                        .HasForeignKey("ProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Profile");
                });

            modelBuilder.Entity("STEMwise.Domain.Entities.University", b =>
                {
                    b.HasOne("STEMwise.Domain.Entities.Country", "Country")
                        .WithMany("Universities")
                        .HasForeignKey("CountryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Country");
                });

            modelBuilder.Entity("STEMwise.Domain.Entities.UserUniversity", b =>
                {
                    b.HasOne("STEMwise.Domain.Entities.Profile", "Profile")
                        .WithMany("UserUniversities")
                        .HasForeignKey("ProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("STEMwise.Domain.Entities.Program", "Program")
                        .WithMany()
                        .HasForeignKey("ProgramId");

                    b.HasOne("STEMwise.Domain.Entities.University", "University")
                        .WithMany()
                        .HasForeignKey("UniversityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Profile");

                    b.Navigation("Program");

                    b.Navigation("University");
                });

            modelBuilder.Entity("STEMwise.Domain.Entities.VisaConfig", b =>
                {
                    b.HasOne("STEMwise.Domain.Entities.Profile", "Profile")
                        .WithMany("VisaConfigs")
                        .HasForeignKey("ProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Profile");
                });

            modelBuilder.Entity("STEMwise.Domain.Entities.Country", b =>
                {
                    b.Navigation("Universities");
                });

            modelBuilder.Entity("STEMwise.Domain.Entities.Profile", b =>
                {
                    b.Navigation("LoanConfigs");

                    b.Navigation("UserUniversities");

                    b.Navigation("VisaConfigs");
                });

            modelBuilder.Entity("STEMwise.Domain.Entities.University", b =>
                {
                    b.Navigation("Programs");
                });
#pragma warning restore 612, 618
        }
    }
}
